admins:
- 1957520372
forwards:
- source: -1001706470228
  dest:
  - -1001700124411
  offset: 86039
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.0
plugins: {}
