admins: []
forwards:
- source: -1001706470228
  dest:
  - -1001700124411
  offset: 56275
  #end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2
plugins: {}
