admins:
- 1957520372
forwards:
- source: -1001619773080
  dest:
  - -1001547414628
  offset: 10440
  #end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1
plugins: {}
