admins: []
forwards:
- source: -1001782188274
  dest:
  - -1001642348231
  offset: 0
  #end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2
plugins: {}
