admins: []
forwards:
- source: -1001619773080
  dest:
  - -1001717126903
  offset: 0
  #end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1
plugins: {
   files:

      whitelist: [audio,gif,video,video_note,sticker,contact,photo,document,nofile]
      }
