admins: []
forwards:
- source: -1001591494072
  dest:
  - -1001642348231
  offset: 64555
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 0.0
plugins: {}
